<?php session_start(); 
include("pathToGlobalVariables.php");
include($pathToGlobalVariables);
$connPath = relativePath(getcwd(),$conn_php);
include($connPath);

$synonymLinkPath = str_replace('\\','\\\\',relativePath(getcwd(),$results_php)."?searchString=");
 
connect();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Documentation</title>
   	<link rel="stylesheet"  href="http://metRxn.engr.psu.edu/inc/css/sidebars.css"   type="text/css" />
   	<link rel="search" href="/MetRxn/plugins/openSearch/openSearch.xml" type="application/opensearchdescription+xml" title="MetRxn" />
	<link href="<?php echo relativePath(getcwd(),$metRxnContents_css); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo relativePath(getcwd(),$anchors_css); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo relativePath(getcwd(),$headings_css); ?>" rel="stylesheet" type="text/css" />

<style type="text/css">
a:link {
	color: #3032A1;
}
	.header {

		width:100%;
		top:0;
		border:none;


	}
	.search {
		overflow:scroll;
	}
	.footer {
		position:relative;
		bottom:0;
		width:100%;
	}
	.content {
		float:left;
		width:130%;
		position:relative;
		background-position:center;
		
	}
	.leftbar{
		float:left;
		width:20%;
		}
	iframe{
		border:0;		
	}
	table
	{
	border-collapse:collapse;
	margin:20px;
	}
	td
	{
	padding:2px;
	}
	.imageframe {

	}
	img {
		margin:20px;
		float:left;

	}
	#structure {

		float:left;
	}
	#synonym {
		bottom:1;
		float:none;
	}

	</style>
</head>

<body>
<table>
<tr>
<div class="header">
    <iframe src="<?php echo relativePath(getcwd(),$top_data_htm);?>" width="100%" height="160" scrolling="no">
    </iframe>
</div>
</tr>
<tr>
<div class="leftbar">	
   	<iframe src="<?php echo relativePath(getcwd(),$left_Menu_php); ?>" height="450" scrolling="no">
    </iframe>
</div>
<td>
<div>
<p>MetRxn is a knowledgebase that includes standardized metabolite and reaction descriptions by integrating information from databases and
genome-scale metabolic models into a single unified data set. All metabolite entries have matched synonyms, 
resolved protonation states and are linked to unique structures. 
All reaction entries are elementally and charge balanced. This is accomplished through the use of a workflow of lexicographic, 
phonetic, and structural comparison algorithms. MetRxn allows for the download of standardized versions of existing genome-scale 
metabolic models and the use of metabolic information for the rapid reconstruction of new ones. 
By conforming to standardized metabolite and reaction descriptions, 
MetRxn enables users to efficiently perform complex queries and comparisons across models and/or databases. 
For example, common metabolites and/or reactions between models and databases can rapidly be generated along 
with connected paths that link source to target metabolites. MetRxn supports export of selected reactions and models 
in SBML format. 
</p>
<p>
<h3>Source comparisons and visualization</h3>
In addition to listing the content (number of metabolites, reactions, etc.) of the selected data source(s), MetRxn contains many tools for comparing two or more models and visualizing the results. These associations can be for metabolites or reactions. During these comparisons compartment information and reversibility are suppressed. Comparison tables are generated by comparing the associations between the selected data source(s) using the canonical structures.
</p>
<img src="comparision.gif" />
<br></br>
<br></br>

<p>
<h3>Data export and display</h3>
MetRxn supports a number of export capabilities. In general, any list that is displayed contains
 live links to the metabolite or reaction entities. 
 These lists can consist of an entire model, data from a comparison, 
 or query results. All items can be exported to SBML format. 
 In addition, the public MySQL database can be downloaded in its entirety. 
 
</p>
<img src="download.gif" />

</div>
</td>
</tr>
</table>
</body>
</html>
